version: 2

jobs:
  step_two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Doing another thing"

  step_one:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Doing a thing"

workflows:
  version: 2
  build:
    jobs:
      - step_one:
          filters:
            branches:
              only:
                - master

      - step_two:
          requires:
            - step_one
