version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"

  stuff:
    steps:
      - checkout
      - run: echo "A first hello"

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master

      - stuff
