version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"

  workflow_build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"

workflows:
  version: 2
  build:
    jobs:
      - workflow_build:
          filters:
            branches:
              only:
                - master
