version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:15.14.0

commands:
  restore_node_modules:
    steps:
      - restore_cache:
          keys:
            # Download and cache dependencies
            - mfc-gatsby-1.0.0-node_modules-cache-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - mfc-gatsby-1.0.0-node_modules-cache

  npm_install:
    steps:
      - run:
          name: install
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: mfc-gatsby-1.0.0-node_modules-cache-{{ checksum "package-lock.json" }}

  build_and_clean:
    steps:
      - run:
          name: build
          command: npm run build

      - persist_to_workspace:
          root: .
          paths:
            - ./public/

jobs:
  install:
    executor: node-executor
    steps:
      - checkout
      - npm_install

  build_and_clean:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_node_modules
      - build_and_clean

  deploy:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_node_modules
      - run:
          name: deploy
          command: npm run deploy

workflows:
  version: 2
  build:
    jobs:
      - install:
          filters:
            branches:
              only:
                - master

      - build_and_clean:
          requires:
            - install

      - deploy:
          requires:
            - build_and_clean
