version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:10.15.3

commands:
  restore_node_modules:
    steps:
      - restore_cache:
          keys:
            # Download and cache dependencies
            - mfc-gatsby-1.0.0-node_modules-cache-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - mfc-gatsby-1.0.0-node_modules-cache

  yarn_install:
    steps:
      - restore_node_modules

      - run:
          name: yarn
          command: yarn

      - save_cache:
          paths:
            - node_modules
          key: mfc-gatsby-1.0.0-node_modules-cache-{{ checksum "yarn.lock" }}

  build_and_clean:
    steps:
      - run:
          name: build
          command: yarn build

      - persist_to_workspace:
          root: .
          paths:
            - ./public/

jobs:
  install:
    executor: node-executor
    steps:
      - checkout
      - yarn_install

  build_and_clean:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - build_and_clean

workflows:
  version: 2
  build:
    jobs:
      - install:
          filters:
            branches:
              only:
                - master

      - build_and_clean:
          requires:
            - install
